[tool.poetry]
name = "kot-baton-education"
version = "0.1.0"
description = ""
authors = ["Yana Gubskaya <Yana.gubskaja87@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
